name: CI

on: [push, pull_request]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install OTP and Elixir
        uses: erlef/setup-elixir@v1
        with:
          otp-version: '23.1.3'
          elixir-version: "1.12.3"

      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted

  test_linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Compile shim
        run: |
          cd priv && cargo build --release 
          cp target/release/rambo rambo-linux

      - name: Install OTP and Elixir
        uses: erlef/setup-elixir@v1
        with:
          otp-version: '24.1.3'
          elixir-version: '1.12.3'

      - name: Run tests
        run: |
          mix deps.get
          mix test

  test_windows:
    name: Test on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: x86_64-pc-windows-gnu
          toolchain: stable
          override: true

      - name: Compile shim
        run: |
          cd priv && cargo build --release --target x86_64-pc-windows-gnu
          copy target\x86_64-pc-windows-gnu\release\rambo.exe rambo.exe

      - name: Install OTP and Elixir
        uses: erlef/setup-elixir@v1
        with:
          otp-version: '24.1.3'
          elixir-version: '1.12.3'

      - name: Run tests
        run: |
          mix deps.get
          mix test

